name: Setup and Use Environment Variables

on: [push]

jobs:
  test:
    env:
      SAMPLE_ENV_VAR: 'test val'
    runs-on: ubuntu-latest
    steps:
      - name: Print SAMPLE_ENV_VAR
        run: echo "SAMPLE_ENV_VAR=${{ env.SAMPLE_ENV_VAR }}"
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flavor: [plain, rust]
    env:
      SAMPLE_ENV_VAR: ${{ matrix.flavor }}
    steps:
      - name: Print flavor and SAMPLE_ENV_VAR
        run: |
          echo "Flavor: ${{ matrix.flavor }}"
          echo "SAMPLE_ENV_VAR: $SAMPLE_ENV_VAR"
