name: Setup and Use Environment Variables

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    env:
      VAR1: 'value1'
      # This does not reference VAR2 directly
    steps:
      - name: Set VAR2
        run: echo "Creating VAR2 from VAR1"
        shell: bash
        env:
          VAR2: '${{ steps.job1-env.VAR1 }}-suffix'

  job2:
    needs: job1
    runs-on: ubuntu-latest
    env:
      VAR3: '${{ needs.job1.outputs.VAR2 }}'
    steps:
      - name: Use VAR3
        run: echo "VAR3 is set to ${{ env.VAR3 }}"
